#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

//PROJECT_NAME := project_template
PROJECT_NAME := ntpForEsp8266

include $(IDF_PATH)/make/project.mk

