#!/bin/sh /etc/rc.common

start() {
    /mnt/ntp-route/mips-ntp-client 192.168.31.8 &		#pc ip
    /mnt/ntp-route/mips-ntp-server  &
    return 0    # always return ok

}

restart() {
	sleep 1
}


stop() {
	sleep 1
}
